apiVersion: app/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 3
  selector:
    matchLabels: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: ngnix
        image: ngnix
        ports:
        - containerPort: 80